### ISSUE TITLE
V2 Addon?

### ISSUE THREAD

**Issue by NullVoxPopuli** [nickschot/ember-mobile-menu#722]
I'd like to use ember-mobile-menu over at ember-primitives.pages.dev/, but I have a strict no-v1 addons policy (except for `@ember/*` and `ember-source` rn).

It kind of looks like this repo _may_ be mid-process with converting to v2?

Though, I noticed there is still sass -- which is a deal breaker -- https://github.com/nickschot/ember-mobile-menu/issues/73

Do you want help with v2-ification?
I think that way I can `await import` the whole mobile menu _unless_ the screen is of a certain size, which means I can include the mobile menu at all times, but not pay for it on desktop screen sizes!

**Comment by nickschot** [comment]
Hiya! Yes indeed, I had converted the add-on to a mono repo kind of early on to separate the (addon-docs) docs etc. app from the add-on code which started to be complex to maintain.

I think the time is now ripe for a proper v2 add-on though.

There is no reason really that this add-on would still require sass or nesting. This was mostly to provide the option (when the host app uses ember-cli-sass) to import and customise it from there. The add-on also ships compiled CSS.

I think we can still provide customisation through css variables as a potential alternative for that.

What I'd like to do is ship the current pre-release as a stable release first, since it fixes the build for existing apps. Help with v2 conversion is of course appreciated.

If you have a strict no-v1 addons policy, we may also need to convert https://github.com/nickschot/ember-gesture-modifiers which is used internally. That should be straightforward though, since it really only has 1 modifier and some test helpers.

**Comment by nickschot** [comment]
Put some work into it today, I got a v2 addon working locally (after dependency hell earlier today 🔥)

I need to at the very least revamp the CSS (approach) as you already identified, but otherwise it appears to already work.

**Comment by nickschot** [comment]
I've done a pre-release of the v2 addon (v5.0.0-0). 

I have not updated the docs (mostly regarding the SCSS -> CSS) yet and also want to get in
- ember-gesture-modifiers v2 addon (doesn't exist yet)
- #776 

But! it is ready to try.

**Comment by NullVoxPopuli** [comment]
yay!

**Comment by NullVoxPopuli** [comment]
This is working great! I'm going to close
